"""Add location to Tournament and create TournamentWinner model

Revision ID: 200e2832e39d
Revises: 711ed3e61c89
Create Date: 2025-08-11 18:24:51.835249

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "200e2832e39d"
down_revision = "711ed3e61c89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournament_winner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("placing", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournament.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tournament", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tournament", schema=None) as batch_op:
        batch_op.drop_column("location")

    op.drop_table("tournament_winner")
    # ### end Alembic commands ###
